// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/get_all_projects.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/get_all_projects.go -destination=./mocks/mock_get_all_projects.go -package=resthandlmocks
//

// Package resthandlmocks is a generated GoMock package.
package resthandlmocks

import (
	context "context"
	getallmodel "projectservice/internal/usecase/models/getallprojects"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetAllProjectsUsecase is a mock of GetAllProjectsUsecase interface.
type MockGetAllProjectsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAllProjectsUsecaseMockRecorder
	isgomock struct{}
}

// MockGetAllProjectsUsecaseMockRecorder is the mock recorder for MockGetAllProjectsUsecase.
type MockGetAllProjectsUsecaseMockRecorder struct {
	mock *MockGetAllProjectsUsecase
}

// NewMockGetAllProjectsUsecase creates a new mock instance.
func NewMockGetAllProjectsUsecase(ctrl *gomock.Controller) *MockGetAllProjectsUsecase {
	mock := &MockGetAllProjectsUsecase{ctrl: ctrl}
	mock.recorder = &MockGetAllProjectsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAllProjectsUsecase) EXPECT() *MockGetAllProjectsUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAllProjectsUsecase) Execute(ctx context.Context, in *getallmodel.GetAllProjectsInput) (*getallmodel.GetAllProjectsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*getallmodel.GetAllProjectsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAllProjectsUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAllProjectsUsecase)(nil).Execute), ctx, in)
}
