// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/delete_project.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/delete_project.go -destination=./mocks/mock_delete_project.go -package=resthandlmocks
//

// Package resthandlmocks is a generated GoMock package.
package resthandlmocks

import (
	context "context"
	deletemodel "projectservice/internal/usecase/models/deleteproject"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteProjectUsecase is a mock of DeleteProjectUsecase interface.
type MockDeleteProjectUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteProjectUsecaseMockRecorder
	isgomock struct{}
}

// MockDeleteProjectUsecaseMockRecorder is the mock recorder for MockDeleteProjectUsecase.
type MockDeleteProjectUsecaseMockRecorder struct {
	mock *MockDeleteProjectUsecase
}

// NewMockDeleteProjectUsecase creates a new mock instance.
func NewMockDeleteProjectUsecase(ctrl *gomock.Controller) *MockDeleteProjectUsecase {
	mock := &MockDeleteProjectUsecase{ctrl: ctrl}
	mock.recorder = &MockDeleteProjectUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteProjectUsecase) EXPECT() *MockDeleteProjectUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteProjectUsecase) Execute(ctx context.Context, in *deletemodel.DeleteProjectInput) (*deletemodel.DeleteProjectOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*deletemodel.DeleteProjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteProjectUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteProjectUsecase)(nil).Execute), ctx, in)
}
