// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../repository/session/sessionrepo.go
//
// Generated by this command:
//
//	mockgen -source=./../../../repository/session/sessionrepo.go -destination=mocks/mock_session.go -package=logmocks
//

// Package logmocks is a generated GoMock package.
package logmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepo is a mock of SessionRepo interface.
type MockSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoMockRecorder
	isgomock struct{}
}

// MockSessionRepoMockRecorder is the mock recorder for MockSessionRepo.
type MockSessionRepoMockRecorder struct {
	mock *MockSessionRepo
}

// NewMockSessionRepo creates a new mock instance.
func NewMockSessionRepo(ctrl *gomock.Controller) *MockSessionRepo {
	mock := &MockSessionRepo{ctrl: ctrl}
	mock.recorder = &MockSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepo) EXPECT() *MockSessionRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSessionRepo) Get(ctx context.Context, sessionId string) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionId)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionRepoMockRecorder) Get(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionRepo)(nil).Get), ctx, sessionId)
}

// Save mocks base method.
func (m *MockSessionRepo) Save(ctx context.Context, sessionId string, userId uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, sessionId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionRepoMockRecorder) Save(ctx, sessionId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionRepo)(nil).Save), ctx, sessionId, userId)
}
